### ISSUE TITLE
How to use the Run_TrackMate_Headless.groovy file

### ISSUE THREAD

**Issue by ShuhaoGithub** [fiji/TrackMate#156]
Thank you for the fantastic plugin. May I ask how to use the Run_TrackMate_Headless.groovy? I tried to run it as a macro program but it did not work. Thank you!

**Comment by imagejan** [comment]
@ShuhaoGithub several options:

* drag it to your Fiji window, then it'll open in the script editor, and you can press <kbd>Run</kbd>
* save the file into a subdirectory of `Fiji.app/scripts/`, (e.g. `Fiji.app/scripts/MyScripts`), then it will be available as a menu command (*MyScripts > Run TrackMate Headless*) and will be recorded by the macro recorder.

Hope that helps.

For further questions like these, I recommend asking on https://forum.image.sc instead of opening an issue here.
