### ISSUE TITLE
Upload newer version of OpenCSV to Fiji.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#176]
Fiji ships the v3.9 of OpenCSV but the version declared in the scijava parent pom 30.0.0 is v5.2. We need to upload this one.

**Comment by imagejan** [comment]
The state of the *Java-8* update site is currently in sync with `pom-scijava-29.2.1` (except for some artifacts that were uploaded manually), whereas the update to OpenCSV 5.2 happened in `pom-scijava-30.0.0`. Please wait for the big Fiji upload by @ctrueden to avoid any breakages.

**Comment by ctrueden** [comment]
I ran the melting pot on Fiji with TrackMate 7.0.3. Here are the failures:

| Component                           | Reason |
|-------------------------------------|--------|
| sc.fiji/fiji                        | TBD    |
| net.imagej/imagej-notebook          | TBD    |
| net.imagej/imagej-ops               | TBD    |
| net.imglib2/imglib2-label-multisets | TBD    |
| net.imglib2/imglib2-roi             | TBD    |
| org.scijava/jep                     | TBD    |
| sc.fiji/FilamentDetector            | TBD    |
| sc.fiji/Kappa                       | TBD    |
| sc.fiji/KymographBuilder            | TBD    |
| sc.fiji/fiji-lib                    | TBD    |
| sc.fiji/trakem2_tps                 | TBD    |

Many/most of these failures are probably unrelated to TrackMate and OpenCSV. I will edit this comment as I investigate each and chart the reason for each failure, and whether action is needed to resolve it.

**Comment by ctrueden** [comment]
* Need to release pom-scijava 31.0.0 with several preemptive version bumps to address the `TrackMate_`-to-`TrackMate` rename, with at least the following:
    * FilamentDetector 1.0.1
    * MaMuT 0.30.1
    * imagej 2.3.0
    * fiji 2.3.0
* Need to track down why the melting pot is detecting an opencsv 2.1 in addition to opencsv 5.2. Might be due to two different groupIds, maybe the very old `au.com.bytecode` groupId.
* Need to remove the opencsv 3.9 version pin from BigWarp.
* MaMuT has been added to pom-scijava; Mastodon needs to be updated to extend pom-scijava 31 at a not-hardcoded version. Mastodon needs to depend on TrackMate, not TrackMate_. The jgrapht exclusion needs to be removed if possible, or added to pom-scijava dependencyManagement if truly necessary.
* SciJava Common 2.86.1 needs to be released. But it cannot be released until we fix the GitHub Actions CI infrastructure to sign JARs correctly with GPG, so that it can be deployed to OSS Sonatype successfully.
* FilamentDetector needs 1.0.1 release extending pom-scijava 31 and depending on TrackMate, not TrackMate_.
* fmi-trackmate-addons, TrackMate-extras, and TrackMate-TrackAnalysis need update from TrackMate_ to TrackMate.

Work on these goals will continue on Tuesday...

**Comment by tinevez** [comment]
# MaMuT 

MaMuT has been brought in line with the new TrackMate v7 series.
- It has been renamed from `MaMuT_` to `MaMuT` 
- Version 7.0.1 has been released.

It is based right now on `pom--scijava v30.0.0` but I had to enforce certain imglib2 artifact versions:
```
		<bigdataviewer-core.version>10.2.0</bigdataviewer-core.version>
		<bigdataviewer-vistools.version>1.0.0-beta-28</bigdataviewer-vistools.version>
```

**Comment by tinevez** [comment]
# Mastodon.

Still working on it. I have a JUnit test for an exporter that fails for now, I am still investigating here: https://github.com/mastodon-sc/mastodon/tree/dev

However, this SNAPSHOT depends on TrackMate v70.4 and MaMuT v7.0.1 and works.
I removed the exclusion section for `jgrapht` in the MaMuT dep declaration, and this did not seem to have a negative impact on the deploy to Fiji thing.

**Comment by tinevez** [comment]
# TrackMate-extras and TrackMate-TrackAnalysis 

They can be **entirely removed**. Their features have been merged into the new TrackMate. 
I will archive the repos after the mega melt.

**Comment by tinevez** [comment]
# fmi-trackmate-addons

I have a made a PR for the TrackMate update here: https://github.com/fmi-faim/fmi-trackmate-addons/pull/18

Still under review by @imagejan

**Comment by tinevez** [comment]
Solved with TrackMate v7, released today.
