### ISSUE TITLE
TrackMate depends on deprecated classes.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#53]
Since we move the pom-fiji 5.0, some classes are marked deprecated, particularly those coming from the late imglib2-meta:

 net.imglib2.meta.Axes
 net.imglib2.meta.AxisType
 net.imglib2.meta.ImgPlus
 net.imglib2.meta.view.HyperSliceImgPlus
 net.imglib2.meta.axis.DefaultLinearAxis
 net.imglib2.meta.ImgPlusMetadata

and multithreading:
 net.imglib2.multithreading.SimpleMultiThreading

We need to replace them by suitable classes.

**Comment by tinevez** [comment]
Yesterday @hinerm did the change:
6f4e15d5f2d64466fb23b9e707748d7a5be2d3ec
But the target imports are still deprecated.

**Comment by dscho** [comment]
> But the target imports are still deprecated.

Do you mean the classes `ImgPlus`, `HyperSliceImgPlus`, or the methods of `SimpleMultiThreading`? If you refer to the former, there are no replacements yet (the `@deprecated` annotation is not *quite* correct because of that, but there is a `@dontUseItWillGoAway` annotation). If you are referring to the latter: it is much better to use the SciJava `ThreadService` which has a chance – as opposed to the `SimpleMultiThreading`  class – to be context sensitive, e.g. reducing the number of threads in a cluster environment to avoid being kicked off and banned by the cluster administrator.

Those three issues are the only warnings I see in Eclipse as of the current `master`...

**Comment by tinevez** [comment]
Hi @dscho 
This issue tracks the 2 categories of classes. 
Regarding the `ImgPlus` and co., I am standing still.
Regarding mutithreading, I am blocked at one point. I need something like an ExecutorService but that would be able to tell roughly how many threads it ships to fine tune tasks. I think there was a discussion started revolving around this point but I could not find it again.
In the meantime, I am standing still.

**Comment by hinerm** [comment]
@tinevez - for some background, the `net.imglib2.meta` > `net.imagej` migration started as a result of https://github.com/imagej/imagej-common/issues/43
So the goal wasn't to remove deprecated classes, but to cleanse `net.imglib2.meta`
