### ISSUE TITLE
Add some trajectory characteristics which are provided by TraJ

### ISSUE THREAD

**Issue by thorstenwagner** [fiji/TrackMate#81]
I would like to suggest to add some trajectory characteristics which are provided by the library TraJ:
https://github.com/thorstenwagner/TraJ

**Comment by tinevez** [comment]
Do you feel like doing it? 

* You can add them as a or several TrackAnalyzer that generates the features you want.
* Or write an Action that triggers TraJ, automatically import existing tracks from TrackMate to TraJ and prints the report.

**Comment by thorstenwagner** [comment]
I will implement it... I guess I will start with the **fractal dimension** (because it is a very powerfull feature)  as a **TrackAnalyzer**, and then add (step by step) another features. 
However, it will need some time...

**Comment by tinevez** [comment]
What about just making an action that calls TraJ? 
This should be fast and takes little time.

**Comment by thorstenwagner** [comment]
We could start with a action as well. What kind of report have you in mind?

**Comment by tinevez** [comment]
Nothing fancy: just an IJ1 table. 
I was aiming at an Action rather than a series of TrackFeature for several reasons:

* TrackFeatures are updated "live" everytime something changes in the model. If the feature takes too much time to compute, then it will make the GUI sluggish against manual modifications.
* The Action can call to a 3rd party library. If something goes wrong later or if we make a mistake in dependency management, then the user will receive exceptions only when they launch the action, instead of every single time they edit the model.
- In an action you can ask the user for parameters. I think you need this for some stuff in TraJ.

**Comment by thorstenwagner** [comment]
Good reasons! Then we have a decision :-)

**Comment by tinevez** [comment]
Hi @thorstenwagner 
Is there an update to report about this issue?
